### ISSUE TITLE
How to submit our own model for evaluation?

### ISSUE THREAD

**Issue by SparkJiao** [llmeval/llmeval-2#1]
Great work!

May I know if it is possible to submit our own model for evaluation. We are the contributor to PandaLLM project and we have 13B chat model [weight](https://github.com/dandelionsllm/pandallm#panda-%E6%A8%A1%E5%9E%8B).

Thanks very much!

Best,
Fangkai

**Comment by qzhangFDU** [comment]
Thank you for your attention. We will launch automatic evaluation in LLMEVAL-3. Welcome to participate.

**Comment by SparkJiao** [comment]
Thanks very much! I will pay attention to it.
