### ISSUE TITLE
MOSS-MARS的更多信息及建议

### ISSUE THREAD

**Issue by yucc-leon** [llmeval/llmeval-2#4]
1. 请问这个模型是MOSS模型的哪个版本？网上没有搜到更多信息
2. 不同API、模型的测试效果随时间可能发生一定变化，例如GPT4据称后续在逻辑推理、知识问答等方面的能力被逐渐削弱，所以是否可以附上每个模型评测的具体时间？
3. 目前只有最后的分数没有具体的回答内容公开，是否后续会发布？

**Comment by qzhangFDU** [comment]
moos-mars 这里可以申请https://moss.fastnlp.top/

时间写了，7月5号到9号

各个系统回答的内容也都在发布的同时同步上传了  https://github.com/llmeval/llmeval-2/tree/master/data
