### ISSUE TITLE
给gpt4的prompt中需要有hint吗

### ISSUE THREAD

**Issue by MelodyChenjun** [llmeval/llmeval-2#5]
我看到gpt4的prompt模板中，没有hint，但是result给的数据里有hint，这个prompt需要加入hint吗
![image](https://github.com/llmeval/llmeval-2/assets/100499853/fcb5e391-c32c-475f-9f24-c3e4086466cf)

**Comment by MelodyChenjun** [comment]
还有一个问题请教，为什么客观题的prompt中说1-2star，但是result里面却有3
![image](https://github.com/llmeval/llmeval-2/assets/100499853/e9a0dceb-7367-4fbb-8da7-e3d5ecb9d584)

**Comment by Shichun-Liu** [comment]
您好！
第一个问题：本次实验中输入给GPT-4的Prompt不会把hint字段输入，hint字段仅保留给数据分析阶段使用以评判打分质量；
第二个问题：result里面的3分是GPT-4生成的幻觉情况，在统计时统一记为2分。这种情况在我们的全体测试数据中占少数，我们近期将会更新处理后的测试数据。
感谢您的关注！

**Comment by KongLongGeFDU** [comment]
您好，欢迎关注LLMEVAL！
关于您的第一个问题，我们在本次评测中无论是人工评测或者是GPT4自动评测，都没有使用到hint字段。hint字段主要是用于后续的数据分析的参考。
关于您的第二个问题i，我们的网页端客观题是1-2stars，因此在提供prompt的时候也是这么提问的。但是在数据分析阶段，我们为了提升正确性的相对比重，采用了如下的映射：
客观题 Correctness：1star=1score；2stars=3score
主观题 Accuracy：1star=1score；2stars=3score；3stars=5score
希望能解决您的疑惑！

**Comment by KongLongGeFDU** [comment]
您好，欢迎关注LLMEVAL！
关于您的第一个问题，我们在本次评测中使用到了hint字段，具体在这个部分。
![image](https://github.com/llmeval/llmeval-2/assets/108411902/8013e8dd-741b-4f9f-8608-78d998393953)
但是因为大多主观题没有标注答案，我们这个字段有许多的值为“/”
关于您的第二个问题，客观题Correctness部分我们的网页端采用的是1-2stars；主观题Accuracy采用的是1-3stars，因此在提供prompt的时候也是这么提问的。
在数据分析阶段，我们为了提升正确性的相对比重，采用了如下的映射：
客观题 Correctness：1star=1score；2stars=3score
主观题 Accuracy：1star=1score；2stars=3score；3stars=5score
希望能解决您的疑惑！

**Comment by KongLongGeFDU** [comment]
您好，欢迎关注LLMEVAL！
关于您的第一个问题，我们在本次评测中使用到了hint字段，具体在这个部分。
![image](https://github.com/llmeval/llmeval-2/assets/108411902/8013e8dd-741b-4f9f-8608-78d998393953)
但是因为大多主观题没有标注答案，我们这个字段有许多的值仅供参考。
关于您的第二个问题，客观题Correctness部分我们的网页端采用的是1-2stars；主观题Accuracy采用的是1-3stars，因此在提供prompt的时候也是这么提问的。
在数据分析阶段，我们为了提升正确性的相对比重，采用了如下的映射：
客观题 Correctness：1star=1score；2stars=3score
主观题 Accuracy：1star=1score；2stars=3score；3stars=5score
希望能解决您的疑惑！
